class TextApp {
  static const String loading = "Cargando...";
  static const String signup = "Registrarse";
  static const String usuario = "Usuario";
  static const String perfilProfesional = "Profesional";
  static const String back = "Volver";
  static const String rut = "Rut: 11.111.222-3";
  static const String password = "Contraseña";
  static const String forgotpass = "Recupera o cambia clave AQUÍ";
  static const String or = "o";
  static const String iniciosesion = "Iniciar Sesión";
  static const String googlesign = "Iniciar Sesión con Google";
  static const String donthaveaccount = "¿No tienes una cuenta?";
  static const String name = "Nombre de Usuario";
  static const String apaterno = "Apellido Paterno";
  static const String amaterno = "Apellido Materno";
  static const String email = "Correo Electrónico";
  static const String phone = "Teléfono";
  static const String sexo = "Sexo";
  static const String fnacimiento = "Fecha de Nacimiento";
  static const String logout = "Cerrar Sesión";
  static const String glucosa = 'Nivel de Glucosa (mg/dL)';
  static const String presion = 'Presión Arterial (mmHg)';
  static const String medicamento = 'Medicamentos';
  static const String peso = 'Peso';
  static const String biometria = 'Iniciar con biometría';
  static const String savedatossalud = 'Guardar Datos';
  static const String editarperfil = 'Editar Perfil';
}
